export const EXHIBITION_CATEGORIES = [
  { id: 'cat-1', name: 'Permanent Exhibition', description: 'Core long-term museum displays highlighting major historical milestones.', count: 5, status: 'Active' },
  { id: 'cat-2', name: 'Temporary Exhibition', description: 'Rotating seasonal exhibitions featured for limited timeframes.', count: 4, status: 'Active' },
  { id: 'cat-3', name: 'Traveling Exhibition', description: 'Mobile artifact showcases shared with regional partner institutions.', count: 2, status: 'Active' },
  { id: 'cat-4', name: 'Historical Exhibition', description: 'Detailed chronological narratives of battle tactics, treaties, and diplomacy.', count: 3, status: 'Active' },
  { id: 'cat-5', name: 'Cultural Exhibition', description: 'Spotlight on living heritage, traditional craftsmanship, and attire.', count: 3, status: 'Active' },
  { id: 'cat-6', name: 'Educational Exhibition', description: 'Interactive learning zones designed for school groups and young visitors.', count: 2, status: 'Active' },
  { id: 'cat-7', name: 'Special Exhibition', description: 'VIP exclusive commemorative installations and commemorative events.', count: 1, status: 'Active' },
];

export const MOCK_ARTIFACTS_FOR_ASSIGNMENT = [
  { id: 'art-101', name: 'Royal Ceremonial Sword of Empress Taytu', category: 'weapon', location: 'Vault A - Shelf 3', image: 'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Assigned' },
  { id: 'art-102', name: 'Hand-woven Silk Battle Canopy (Shamah)', category: 'textile', location: 'Hall 02 - Display Case 4', image: 'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Assigned' },
  { id: 'art-103', name: 'Original Treaty Manuscript of 1896', category: 'document', location: 'Archive Room B', image: 'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Available' },
  { id: 'art-104', name: 'Bronze Commemorative Medallion', category: 'coin', location: 'Display Case 12', image: 'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Available' },
  { id: 'art-105', name: 'Embossed Leather Saddle of Menelik II', category: 'ceremonial', location: 'Vault C', image: 'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Available' },
  { id: 'art-106', name: 'Silver Filigree Processional Cross', category: 'jewelry', location: 'Gallery 1', image: 'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=300&q=80', status: 'Assigned' },
];

export const INITIAL_EXHIBITIONS = [
  {
    id: 'ex-1',
    title: 'The Lion of Adwa: Memory & Making',
    subtitle: 'A material history of courage, craft, and victory.',
    category: 'Permanent Exhibition',
    description: 'Explore the strategic brilliance, unity, and enduring legacy of the Battle of Adwa through 42 rare physical artifacts, oral histories, and interactive digital installations.',
    theme: 'Heroic Resilience & Heritage',
    coverImage: 'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=1000&q=80',
    galleryImages: [
      'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
      'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=600&q=80',
      'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    startDate: '2024-10-04',
    endDate: '2025-12-31',
    openingTime: '09:00',
    closingTime: '18:00',
    hall: 'Hall 02',
    roomNumber: 'Room 2B',
    capacity: 250,
    status: 'Active',
    featured: true,
    publicVisibility: true,
    curator: 'Hana Bekele',
    visitorCount: 18462,
    assignedArtifactIds: ['art-101', 'art-102', 'art-106'],
    qrCode: 'ADWA-EX-001',
  },
  {
    id: 'ex-2',
    title: 'Threads of Belonging',
    subtitle: 'Traditional textiles, royal attire, and warrior regalia.',
    category: 'Cultural Exhibition',
    description: 'An intimate showcase of authentic 19th-century garments, hand-woven silk cloaks, and insignia worn by key leaders and patriots.',
    theme: 'Textile Mastery & Identity',
    coverImage: 'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=1000&q=80',
    galleryImages: [
      'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    startDate: '2024-11-01',
    endDate: '2025-05-30',
    openingTime: '09:30',
    closingTime: '17:30',
    hall: 'Hall 01',
    roomNumber: 'Room 1A',
    capacity: 180,
    status: 'Active',
    featured: false,
    publicVisibility: true,
    curator: 'Dagmawi Alemu',
    visitorCount: 12918,
    assignedArtifactIds: ['art-102'],
    qrCode: 'ADWA-EX-002',
  },
  {
    id: 'ex-3',
    title: 'Echoes in Bronze & Parchment',
    subtitle: 'Diplomatic treaties, weaponry, and cartography.',
    category: 'Historical Exhibition',
    description: 'Uncovering original letters, peace treaties, and artillery maps that reshaped international diplomacy at the turn of the century.',
    theme: 'Diplomacy & Strategy',
    coverImage: 'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=1000&q=80',
    galleryImages: [
      'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    startDate: '2024-12-15',
    endDate: '2025-08-20',
    openingTime: '10:00',
    closingTime: '17:00',
    hall: 'Hall 03',
    roomNumber: 'Room 3C',
    capacity: 200,
    status: 'Upcoming',
    featured: false,
    publicVisibility: true,
    curator: 'Mulugeta Abeje',
    visitorCount: 8406,
    assignedArtifactIds: ['art-103'],
    qrCode: 'ADWA-EX-003',
  },
  {
    id: 'ex-4',
    title: 'Learning from the Field',
    subtitle: 'Youth interactive educational gallery.',
    category: 'Educational Exhibition',
    description: 'Hands-on discovery zone for students and school visits to experience historical reenactments and digital storytelling.',
    theme: 'Interactive History',
    coverImage: 'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=1000&q=80',
    galleryImages: [],
    startDate: '2025-01-10',
    endDate: '2025-06-15',
    openingTime: '08:30',
    closingTime: '16:30',
    hall: 'Education Wing',
    roomNumber: 'Studio 1',
    capacity: 120,
    status: 'Draft',
    featured: false,
    publicVisibility: false,
    curator: 'Hana Bekele',
    visitorCount: 5180,
    assignedArtifactIds: [],
    qrCode: 'ADWA-EX-004',
  },
  {
    id: 'ex-5',
    title: 'Victory Centennial Retrospective',
    subtitle: 'Archival photographs and audio recordings.',
    category: 'Special Exhibition',
    description: 'A retrospective honoring the 100th anniversary commemorations with rare audio recordings and archival photos.',
    theme: 'Centennial Memory',
    coverImage: 'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=1000&q=80',
    galleryImages: [],
    startDate: '2024-01-01',
    endDate: '2024-09-30',
    openingTime: '09:00',
    closingTime: '17:00',
    hall: 'Hall 04',
    roomNumber: 'Main Pavilion',
    capacity: 300,
    status: 'Completed',
    featured: false,
    publicVisibility: true,
    curator: 'Wakjira Tesfaye',
    visitorCount: 22400,
    assignedArtifactIds: [],
    qrCode: 'ADWA-EX-005',
  },
];

export const exhibitionDashboardData = {
  kpis: [
    { label: 'Total Exhibitions', value: '20', delta: '+3 this quarter', icon: 'collection' },
    { label: 'Active Exhibitions', value: '12', delta: 'Currently open', icon: 'collection' },
    { label: 'Upcoming Exhibitions', value: '5', delta: 'Scheduled next', icon: 'collection' },
    { label: 'Total Visitors', value: '67.4k', delta: '+14.2% YoY', icon: 'visitors' },
  ],
  visitorTrend: [
    { month: 'Jan', visitors: 18000, goal: 21000 },
    { month: 'Feb', visitors: 20500, goal: 22000 },
    { month: 'Mar', visitors: 23800, goal: 24000 },
    { month: 'Apr', visitors: 21900, goal: 25000 },
    { month: 'May', visitors: 27800, goal: 28000 },
    { month: 'Jun', visitors: 31400, goal: 30000 },
    { month: 'Jul', visitors: 29300, goal: 32000 },
    { month: 'Aug', visitors: 36500, goal: 34000 },
    { month: 'Sep', visitors: 34200, goal: 36000 },
    { month: 'Oct', visitors: 39200, goal: 38000 },
    { month: 'Nov', visitors: 42800, goal: 40000 },
  ],
  popularity: [
    { title: 'The Lion of Adwa', visitors: '18,462 visitors', share: '92%' },
    { title: 'Threads of Belonging', visitors: '12,918 visitors', share: '78%' },
    { title: 'Echoes in Bronze', visitors: '8,406 visitors', share: '64%' },
    { title: 'Learning from the Field', visitors: '5,180 visitors', share: '41%' },
  ],
  statuses: [
    { label: 'Active', count: '12', width: '86%', className: 'bg-smrmp-green' },
    { label: 'Upcoming', count: '05', width: '58%', className: 'bg-smrmp-gold' },
    { label: 'Draft', count: '03', width: '34%', className: 'bg-[#315E8A]' },
    { label: 'Completed', count: '02', width: '23%', className: 'bg-[#9A3A2A]' },
  ],
  schedule: [
    { time: '09:00 - 18:00', title: 'Museum Public Hours', detail: 'All main halls accessible' },
    { time: '10:30', title: 'Guided Curator Tour: The Lion of Adwa', detail: 'Hall 02 · Language: EN / AM' },
    { time: '14:30', title: 'Student Workshop: Living Heritage', detail: 'Education Wing · Room 1' },
    { time: '16:00', title: 'Curator Lecture: Victory & Cartography', detail: 'Hall 03 · Auditorium' },
  ],
};

export const formatVisitorCount = (value) => new Intl.NumberFormat('en-US').format(value);
