export const MAINTENANCE_ROLES = {
  OFFICER: 'maintenance',
};

export const MAINTENANCE_TRANSLATIONS = {
  en: {
    title: 'Maintenance Management',
    subtitle: 'Comprehensive control center for museum facility, artifact, equipment, and security maintenance.',
    portal: 'Maintenance Officer Portal',
    dashboard: 'Dashboard',
    requests: 'Requests',
    createRequest: 'Create Request',
    assignedTasks: 'Assigned Tasks',
    emergency: 'Emergency Incidents',
    artifactDamage: 'Artifact Damage',
    equipment: 'Equipment Issues',
    facility: 'Facility Issues',
    calendar: 'Maintenance Calendar',
    history: 'Repair History',
    reports: 'Reports & Analytics',
    quickEmergency: 'Report Emergency',
    totalRequests: 'Total Requests',
    newRequests: 'New Requests',
    pendingApproval: 'Pending Approval',
    assignedRequests: 'Assigned Requests',
    inProgress: 'In Progress',
    completedRepairs: 'Completed Repairs',
    emergencyRequests: 'Emergency Requests',
    highPriority: 'High Priority',
  },
  om: {
    title: 'Bulchiinsa Suphaa',
    subtitle: 'Giddu-gala to\'ooannoo suphaa meeshaalee seenaa, ijaarsotaa fi dhaabbata muuziyamiif.',
    portal: 'Portal Qondaala Suphaa',
    dashboard: 'Daashboordii',
    requests: 'Gaaffilee Suphaa',
    createRequest: 'Gaaffi Garaa Biraa',
    assignedTasks: 'Hojiiwwan Kenhaman',
    emergency: 'Balaawwan Ariifachiisaa',
    artifactDamage: 'Badiisa Meeshaalee',
    equipment: 'Rakkina Meeshaalee',
    facility: 'Rakkina Gamoo',
    calendar: 'Dhaha Suphaa',
    history: 'Seenaa Suphaa',
    reports: 'Gabaasaa fi Xiinxala',
    quickEmergency: 'Balaa Ariifachiisaa',
    totalRequests: 'Ida\'ama Gaaffilee',
    newRequests: 'Gaaffilee Haaraa',
    pendingApproval: 'Mirkaneessa Eegaa',
    assignedRequests: 'Gaaffilee Kenhaman',
    inProgress: 'Hojii Irra Jira',
    completedRepairs: 'Suphaa Xumurame',
    emergencyRequests: 'Gaaffilee Ariifachiisaa',
    highPriority: 'Priooritii Ol\'aanaa',
  },
  am: {
    title: 'የጥገና አስተዳደር',
    subtitle: 'የቤተ-መዘክሩ የቅርሶች፣ የመሳሪያዎች፣ የሕንፃዎች እና የደህንነት ጥገናዎች ማዕከል::',
    portal: 'የጥገና መኮንን ፖርታል',
    dashboard: 'ዳሽቦርድ',
    requests: 'የጥገና ጥያቄዎች',
    createRequest: 'ጥያቄ ፍጠር',
    assignedTasks: 'የተመደቡ ስራዎች',
    emergency: 'አስቸኳይ አደጋዎች',
    artifactDamage: 'የቅርሶች ጉዳት',
    equipment: 'የመሳሪያዎች ችግር',
    facility: 'የሕንፃ ችግር',
    calendar: 'የጥገና ቀን መቁጠሪያ',
    history: 'የጥገና ታሪክ',
    reports: 'ሪፖርቶች እና ትንታኔዎች',
    quickEmergency: 'አስቸኳይ አደጋ ሪፖርት',
    totalRequests: 'ጠቅላላ ጥያቄዎች',
    newRequests: 'አዲስ ጥያቄዎች',
    pendingApproval: 'ማጽደቅ የሚጠብቁ',
    assignedRequests: 'የተመደቡ ጥያቄዎች',
    inProgress: 'በስራ ላይ ያሉ',
    completedRepairs: 'የተጠናቀቁ ጥገናዎች',
    emergencyRequests: 'አስቸኳይ ጥያቄዎች',
    highPriority: 'ከፍተኛ ቅድሚያ',
  },
};

export const ISSUE_CATEGORIES = [
  { value: 'Artifact Damage', label: 'Artifact Damage', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { value: 'Equipment Failure', label: 'Equipment Failure', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { value: 'Facility Issue', label: 'Facility Issue', color: 'bg-indigo-100 text-indigo-900 border-indigo-300' },
  { value: 'Security Issue', label: 'Security Issue', color: 'bg-red-100 text-red-900 border-red-300' },
];

export const PRIORITY_LEVELS = [
  { value: 'Low', label: 'Low', color: 'bg-slate-100 text-slate-800 border-slate-300', dot: 'bg-slate-500' },
  { value: 'Medium', label: 'Medium', color: 'bg-blue-100 text-blue-800 border-blue-300', dot: 'bg-blue-500' },
  { value: 'High', label: 'High', color: 'bg-amber-100 text-amber-800 border-amber-300', dot: 'bg-amber-500' },
  { value: 'Critical', label: 'Critical', color: 'bg-rose-100 text-rose-800 border-rose-300', dot: 'bg-rose-600' },
];

export const STATUS_STAGES = [
  { value: 'New', label: 'New', color: 'bg-blue-100 text-blue-800 border-blue-300' },
  { value: 'Pending Review', label: 'Pending Review', color: 'bg-purple-100 text-purple-800 border-purple-300' },
  { value: 'Approved', label: 'Approved', color: 'bg-teal-100 text-teal-800 border-teal-300' },
  { value: 'Rejected', label: 'Rejected', color: 'bg-rose-100 text-rose-800 border-rose-300' },
  { value: 'Assigned', label: 'Assigned', color: 'bg-indigo-100 text-indigo-800 border-indigo-300' },
  { value: 'In Progress', label: 'In Progress', color: 'bg-amber-100 text-amber-800 border-amber-300' },
  { value: 'Waiting for Parts', label: 'Waiting for Parts', color: 'bg-orange-100 text-orange-800 border-orange-300' },
  { value: 'Completed', label: 'Completed', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' },
  { value: 'Verified', label: 'Verified', color: 'bg-green-100 text-green-900 border-green-300' },
  { value: 'Closed', label: 'Closed', color: 'bg-gray-100 text-gray-800 border-gray-300' },
];

export const DEPARTMENTS_AND_TEAMS = [
  { id: 'dept-1', name: 'Electrical Technician', lead: 'Kebede Alemu', email: 'elec.lead@adwa.museum', phone: '+251 91 122 3344' },
  { id: 'dept-2', name: 'IT Technician', lead: 'Solomon Worku', email: 'it.lead@adwa.museum', phone: '+251 91 233 4455' },
  { id: 'dept-3', name: 'Building Maintenance', lead: 'Girma Tadesse', email: 'building.lead@adwa.museum', phone: '+251 91 344 5566' },
  { id: 'dept-4', name: 'Artifact Conservation Team', lead: 'Selamawit Tesfaye', email: 'conservation@adwa.museum', phone: '+251 91 455 6677' },
  { id: 'dept-5', name: 'Security Team', lead: 'Tewodros Kassahun', email: 'security.lead@adwa.museum', phone: '+251 91 566 7788' },
  { id: 'dept-6', name: 'Cleaning Team', lead: 'Aster Desta', email: 'cleaning.lead@adwa.museum', phone: '+251 91 677 8899' },
];

export const BUILDINGS = [
  'Main Memorial Building',
  'Adwa Victory Gallery Wing',
  'Central Conservation Vault',
  'Administration Block',
  'Visitor Center & Ticketing Plaza',
  'Outdoor Amphitheater',
  'Underground Storage Depot',
];

export const INITIAL_MAINTENANCE_REQUESTS = [
  {
    id: 'MNT-2026-001',
    title: 'Climate Control Humidity Fluctuation in Main Vault',
    category: 'Equipment Failure',
    priority: 'Critical',
    status: 'In Progress',
    reportedBy: 'Selamawit Tesfaye (Conservation)',
    reportDate: '2026-07-25 08:30',
    lastUpdated: '2026-07-25 10:15',
    building: 'Central Conservation Vault',
    floor: 'Basement 1',
    room: 'Vault Room B-04',
    hall: 'Vault Wing',
    artifactId: 'ART-FCY7WO1C',
    artifactName: 'Ethiopian Battle Shield (Gasha)',
    equipmentId: 'EQP-HVAC-02',
    equipmentName: 'Precision HVAC Humidifier Unit #2',
    description: 'Relative humidity levels spiked from 48% to 68% in Vault B-04 due to sensor condensation buildup. Immediate calibration required to prevent leather artifact deterioration.',
    assignedTo: 'Solomon Worku (IT Technician)',
    department: 'IT Technician',
    estimatedCompletion: '2026-07-26',
    isEmergency: true,
    attachments: [
      { id: 'att-1', name: 'humidity_sensor_log.png', type: 'image', url: 'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=600&q=80' },
      { id: 'att-2', name: 'inspection_notes.pdf', type: 'document', url: '#' },
    ],
    timeline: [
      { date: '2026-07-25 08:30', action: 'Request Submitted', user: 'Selamawit Tesfaye', note: 'Automated alert triggered from humidity monitoring sensor.' },
      { date: '2026-07-25 09:00', action: 'Reviewed & Approved', user: 'Maintenance Officer', note: 'High urgency approved for immediate dispatch.' },
      { date: '2026-07-25 09:20', action: 'Assigned to Technician', user: 'Maintenance Officer', note: 'Assigned to HVAC & Sensor specialist Solomon Worku.' },
      { date: '2026-07-25 10:15', action: 'Work In Progress', user: 'Solomon Worku', note: 'Technician on-site testing replacement sensor probe.' },
    ],
    comments: [
      { id: 'c-1', user: 'Selamawit Tesfaye', date: '2026-07-25 08:35', text: 'Shield has been temporarily covered with protective archival cloth.' },
      { id: 'c-2', user: 'Solomon Worku', date: '2026-07-25 10:20', text: 'Replacement digital sensor module is being calibrated now.' },
    ],
  },
  {
    id: 'MNT-2026-002',
    title: 'Flickering LED Spotlight on Emperor Menelik II Portrait',
    category: 'Facility Issue',
    priority: 'Medium',
    status: 'Assigned',
    reportedBy: 'Tigist Bekele (Curator)',
    reportDate: '2026-07-24 14:20',
    lastUpdated: '2026-07-25 09:10',
    building: 'Main Memorial Building',
    floor: '1st Floor',
    room: 'Main Hall - Bay 3',
    hall: 'Victory Hall',
    artifactId: 'ART-TSF4LD8W',
    artifactName: 'Emperor Menelik II Portrait Painting',
    equipmentId: 'EQP-LGT-104',
    equipmentName: 'Museum Grade Spot Focus LED 4000K',
    description: 'Overhead spotlight #14 flickering intermittently causing glare and poor visual experience for gallery visitors.',
    assignedTo: 'Kebede Alemu (Electrical Technician)',
    department: 'Electrical Technician',
    estimatedCompletion: '2026-07-26',
    isEmergency: false,
    attachments: [
      { id: 'att-3', name: 'spotlight_flicker.mp4', type: 'video', url: '#' },
    ],
    timeline: [
      { date: '2026-07-24 14:20', action: 'Request Submitted', user: 'Tigist Bekele', note: 'Reported during daily morning walkthrough.' },
      { date: '2026-07-25 09:10', action: 'Assigned to Technician', user: 'Maintenance Officer', note: 'Kebede Alemu scheduled for evening bulb/driver swap.' },
    ],
    comments: [
      { id: 'c-3', user: 'Kebede Alemu', date: '2026-07-25 09:30', text: 'Will replace LED driver unit after gallery closing hours at 18:00.' },
    ],
  },
  {
    id: 'MNT-2026-003',
    title: 'Cracked Glass Panel on Display Case #12',
    category: 'Artifact Damage',
    priority: 'High',
    status: 'Pending Review',
    reportedBy: 'Security Team Patrol',
    reportDate: '2026-07-25 07:15',
    lastUpdated: '2026-07-25 07:15',
    building: 'Adwa Victory Gallery Wing',
    floor: 'Ground Floor',
    room: 'Gallery A',
    hall: 'Heroic Gallery',
    artifactId: 'ART-P5T4MMLD',
    artifactName: 'Adwa Victory Commemorative Medal',
    equipmentId: 'EQP-DISP-012',
    equipmentName: 'Reinforced UV Glare Glass Case #12',
    description: 'Hairline stress crack observed on upper right corner of protective glass enclosure. No physical contact with inner coin artifact.',
    assignedTo: 'Unassigned',
    department: 'Building Maintenance',
    estimatedCompletion: '2026-07-27',
    isEmergency: false,
    attachments: [
      { id: 'att-4', name: 'cracked_glass_photo.png', type: 'image', url: 'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=600&q=80' },
    ],
    timeline: [
      { date: '2026-07-25 07:15', action: 'Request Submitted', user: 'Security Team Patrol', note: 'Noted during 07:00 security inspection.' },
    ],
    comments: [],
  },
  {
    id: 'MNT-2026-004',
    title: 'Main Entrance Automatic Glass Door Sensor Malfunction',
    category: 'Facility Issue',
    priority: 'High',
    status: 'In Progress',
    reportedBy: 'Visitor Services Desk',
    reportDate: '2026-07-23 11:00',
    lastUpdated: '2026-07-25 11:30',
    building: 'Visitor Center & Ticketing Plaza',
    floor: 'Ground Floor',
    room: 'Main Lobby',
    hall: 'Entrance Plaza',
    artifactId: null,
    artifactName: null,
    equipmentId: 'EQP-DOOR-01',
    equipmentName: 'Dorma Sliding Door Motion Sensor',
    description: 'Automatic entrance door remaining stuck open, causing air draft and dust entry into lobby.',
    assignedTo: 'Girma Tadesse (Building Maintenance)',
    department: 'Building Maintenance',
    estimatedCompletion: '2026-07-25',
    isEmergency: false,
    attachments: [],
    timeline: [
      { date: '2026-07-23 11:00', action: 'Request Submitted', user: 'Visitor Services', note: 'Door failing to close automatically.' },
      { date: '2026-07-23 11:30', action: 'Approved & Assigned', user: 'Maintenance Officer', note: 'Dispatched Girma Tadesse.' },
    ],
    comments: [
      { id: 'c-4', user: 'Girma Tadesse', date: '2026-07-24 16:00', text: 'Waiting for optical alignment belt replacement.' },
    ],
  },
  {
    id: 'MNT-2026-005',
    title: 'Water Leakage in Restroom B2 Ceiling',
    category: 'Facility Issue',
    priority: 'Critical',
    status: 'Completed',
    reportedBy: 'Aster Desta (Cleaning Lead)',
    reportDate: '2026-07-22 15:45',
    lastUpdated: '2026-07-24 10:00',
    building: 'Administration Block',
    floor: 'Basement 2',
    room: 'Restroom B2-Male',
    hall: 'Service Corridor',
    artifactId: null,
    artifactName: null,
    equipmentId: 'EQP-PLMB-88',
    equipmentName: 'Drainage Pipe Joint B2',
    description: 'Dripping water from overhead wastewater pipe near light fixture. Risk of short circuit.',
    assignedTo: 'Girma Tadesse (Building Maintenance)',
    department: 'Building Maintenance',
    estimatedCompletion: '2026-07-23',
    isEmergency: true,
    attachments: [],
    timeline: [
      { date: '2026-07-22 15:45', action: 'Request Submitted', user: 'Aster Desta', note: 'Emergency water drip.' },
      { date: '2026-07-22 16:00', action: 'Approved & Assigned', user: 'Maintenance Officer', note: 'Immediate plumbing shutdown.' },
      { date: '2026-07-23 12:00', action: 'Repair Completed', user: 'Girma Tadesse', note: 'Replaced pipe coupling and resealed joint.' },
      { date: '2026-07-24 10:00', action: 'Verified', user: 'Maintenance Officer', note: 'No leaks observed after 24 hours pressure test.' },
    ],
    comments: [],
  },
  {
    id: 'MNT-2026-006',
    title: 'Interactive Touchscreen Kiosk #4 OS Freeze',
    category: 'Equipment Failure',
    priority: 'Low',
    status: 'Closed',
    reportedBy: 'IT Helpdesk',
    reportDate: '2026-07-20 09:15',
    lastUpdated: '2026-07-21 14:00',
    building: 'Main Memorial Building',
    floor: '2nd Floor',
    room: 'Interactive Zone',
    hall: 'Learning Center',
    artifactId: null,
    artifactName: null,
    equipmentId: 'EQP-SCRN-04',
    equipmentName: '4K Touch Kiosk Display System',
    description: 'Touch interface unresponsive after firmware push. Requires manual reboot and driver update.',
    assignedTo: 'Solomon Worku (IT Technician)',
    department: 'IT Technician',
    estimatedCompletion: '2026-07-21',
    isEmergency: false,
    attachments: [],
    timeline: [
      { date: '2026-07-20 09:15', action: 'Submitted', user: 'IT Helpdesk', note: 'Kiosk touchscreen unresponsive.' },
      { date: '2026-07-21 14:00', action: 'Closed', user: 'Maintenance Officer', note: 'System updated and verified operational.' },
    ],
    comments: [],
  },
];

export const ARTIFACT_DAMAGE_REPORTS = [
  {
    id: 'ADM-001',
    artifactId: 'ART-FCY7WO1C',
    artifactName: 'Ethiopian Battle Shield (Gasha)',
    category: 'Weapon',
    location: 'Gallery A - Display Unit 02',
    damageType: 'Surface Desiccation & Humidity Stress',
    severity: 'Moderate',
    currentCondition: 'Fair',
    reportedBy: 'Selamawit Tesfaye (Conservation Lead)',
    reportedDate: '2026-07-25',
    status: 'Under Inspection',
    damagePhotos: [
      'https://images.pexels.com/photos/27849813/pexels-photo-27849813.png?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    inspectionNotes: 'Minor micro-cracking observed on natural leather shield border caused by vault micro-climate fluctuation.',
    repairRecommendation: 'Apply beeswax & micro-crystalline archival leather balm; stabilize ambient humidity to strict 45-52%.',
  },
  {
    id: 'ADM-002',
    artifactId: 'ART-C6TB5O08',
    artifactName: 'Hand-woven Battle Flag (Dejazmach Unit)',
    category: 'Textile',
    location: 'Conservation Lab - Flat Bed Tray 01',
    damageType: 'Fiber Fraying & Pigment Fading',
    severity: 'High',
    currentCondition: 'Poor',
    reportedBy: 'Tigist Bekele (Curator)',
    reportedDate: '2026-07-18',
    status: 'Conservation In Progress',
    damagePhotos: [
      'https://images.pexels.com/photos/31326473/pexels-photo-31326473.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    inspectionNotes: 'Silk gold threading showing fraying along hemline. UV filter film on display casing required replacement.',
    repairRecommendation: 'Encapsulate in fine silk mesh support and mount on acid-free linen board under 99% UV-blocking acrylic.',
  },
  {
    id: 'ADM-003',
    artifactId: 'ART-EQXQL4UV',
    artifactName: 'Italian Campaign Map (Captured Document)',
    category: 'Document',
    location: 'Archive Vault - Drawer 14',
    damageType: 'Corner Tear & Paper Brittleness',
    severity: 'Low',
    currentCondition: 'Fair',
    reportedBy: 'Archive Staff',
    reportedDate: '2026-07-10',
    status: 'Repaired & Stabilized',
    damagePhotos: [
      'https://images.pexels.com/photos/14950665/pexels-photo-14950665.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ],
    inspectionNotes: '3mm edge tear stabilized using Japanese tissue and wheat starch paste.',
    repairRecommendation: 'Document successfully stabilized and placed in de-acidified archival sleeve.',
  },
];

export const EQUIPMENT_ITEMS = [
  { id: 'EQP-HVAC-01', name: 'Master HVAC Chiller Unit #1', category: 'Air Conditioning', location: 'Plant Room - Roof', status: 'Operational', lastService: '2026-06-15', nextService: '2026-09-15', serial: 'HVAC-ADW-992' },
  { id: 'EQP-HVAC-02', name: 'Precision Humidifier Unit #2', category: 'Air Conditioning', location: 'Central Vault', status: 'Under Maintenance', lastService: '2026-05-10', nextService: '2026-07-26', serial: 'HUM-PRC-401' },
  { id: 'EQP-PROJ-01', name: 'High-Lumen Laser Projector - Amphitheater', category: 'Display Screens', location: 'Main Hall', status: 'Operational', lastService: '2026-04-01', nextService: '2026-10-01', serial: 'PRJ-EPS-881' },
  { id: 'EQP-QR-08', name: 'Handheld Wireless QR Scanners (Set of 10)', category: 'QR Scanners', location: 'Ticketing Plaza', status: 'Operational', lastService: '2026-07-01', nextService: '2026-08-01', serial: 'QRS-ZBR-010' },
  { id: 'EQP-AUD-24', name: 'Multilingual Audio Guide Devices (50 units)', category: 'Audio Guide Devices', location: 'Information Desk', status: 'Needs Inspection', lastService: '2026-03-20', nextService: '2026-07-28', serial: 'AUD-GD-050' },
  { id: 'EQP-SRV-01', name: 'Primary Museum Database Server Rack', category: 'Servers', location: 'IT Server Room B', status: 'Operational', lastService: '2026-07-12', nextService: '2026-08-12', serial: 'SRV-DEL-910' },
  { id: 'EQP-NET-03', name: 'Core Optical Fiber Switch 48-Port', category: 'Networking Equipment', location: 'IT Server Room B', status: 'Operational', lastService: '2026-06-01', nextService: '2026-12-01', serial: 'SWT-CSC-048' },
  { id: 'EQP-PRNT-02', name: 'Thermal Ticket Printer - Counter 2', category: 'Printers', location: 'Ticketing Plaza', status: 'Operational', lastService: '2026-07-05', nextService: '2026-08-05', serial: 'PRN-EPS-202' },
];

export const FACILITY_ITEMS = [
  { id: 'FAC-LGT-01', system: 'Lighting & Spotlights', location: 'Victory Gallery A & B', condition: 'Good', lastInspection: '2026-07-20', notes: 'All main fixtures operational, 1 backup driver replacement scheduled.' },
  { id: 'FAC-ELEC-02', system: 'Main Electrical Distribution Panel', location: 'Substation Room', condition: 'Excellent', lastInspection: '2026-07-15', notes: 'Infrared thermography scan showed normal operating temperatures.' },
  { id: 'FAC-HVAC-01', system: 'Central Air Conditioning & Filtration', location: 'Whole Building', condition: 'Fair', lastInspection: '2026-07-22', notes: 'HEPA air filter replacement due next week.' },
  { id: 'FAC-DRS-04', system: 'Automated Access Doors & Gates', location: 'Main Entrance & Vaults', condition: 'Maintenance Needed', lastInspection: '2026-07-23', notes: 'Lobby motion sensor belt needs replacement.' },
  { id: 'FAC-WTR-01', system: 'Plumbing & Drainage System', location: 'Restrooms & Utility Rooms', condition: 'Good', lastInspection: '2026-07-24', notes: 'Basement joint leak resolved.' },
  { id: 'FAC-FIR-01', system: 'FM200 Fire Suppression & Smoke Alarm', location: 'Vaults & Exhibition Halls', condition: 'Excellent', lastInspection: '2026-07-01', notes: 'Certified pressure & alarm drill passed with 100% compliance.' },
  { id: 'FAC-ROOF-01', system: 'Roof Waterproofing Membrane', location: 'Memorial Main Building', condition: 'Good', lastInspection: '2026-06-30', notes: 'No rain seepage detected during seasonal downpours.' },
  { id: 'FAC-PARK-01', system: 'Visitor Parking Barrier & Solar Lights', location: 'Exterior Plaza', condition: 'Good', lastInspection: '2026-07-10', notes: 'Solar panel glass cleaned and charging at peak capacity.' },
];

export const EMERGENCY_INCIDENTS = [
  {
    id: 'EMG-2026-01',
    type: 'Electrical Hazard',
    title: 'Substation Transformer Spark Warning',
    severity: 'Critical',
    building: 'Substation Room',
    reportedBy: 'Duty Security Officer',
    time: '2026-07-25 06:15',
    status: 'Resolved',
    description: 'Minor electrical arcing sound detected near breaker panel B. Automated circuit breaker tripped successfully.',
    actionsTaken: 'Isolated breaker section B4, switched vault power to UPS backup generator, replaced blown fuse module.',
  },
  {
    id: 'EMG-2026-02',
    type: 'Broken Display Case',
    title: 'Accidental Impact on Display Case #12',
    severity: 'High',
    building: 'Gallery A',
    reportedBy: 'Patrol Officer',
    time: '2026-07-25 07:15',
    status: 'Contained & Monitored',
    description: 'Hairline fracture on outer protective glass casing. Stanchion barriers moved 1 meter back.',
    actionsTaken: 'Artifact inspected by conservator; no structural contact. Replacement glass panel ordered.',
  },
];

export const EMERGENCY_CONTACTS = [
  { name: 'Adwa Museum Fire Command', role: 'Fire & Rescue Unit', phone: '+251 11 111 2233', alt: '+251 91 100 0001' },
  { name: 'Addis Ababa Police Security Liaison', role: 'Police Command', phone: '+251 11 911 0000', alt: '991' },
  { name: 'Dr. Selamawit Tesfaye', role: 'Lead Conservator', phone: '+251 91 455 6677', alt: 'Ext. 104' },
  { name: 'Girma Tadesse', role: 'Facilities Director', phone: '+251 91 344 5566', alt: 'Ext. 102' },
  { name: 'Tewodros Kassahun', role: 'Chief of Security', phone: '+251 91 566 7788', alt: 'Ext. 101' },
  { name: 'Ethiopian Electric Utility Emergency Desk', role: 'Power Utility', phone: '+251 11 155 0000', alt: '905' },
];

export const MAINTENANCE_CALENDAR_EVENTS = [
  { id: 'cal-1', title: 'HVAC Filter Swap - Vault B', date: '2026-07-26', type: 'Scheduled Repair', priority: 'High', department: 'IT Technician' },
  { id: 'cal-2', title: 'Monthly Fire Alarm & Sprinkler Test', date: '2026-07-28', type: 'Inspection Date', priority: 'Medium', department: 'Security Team' },
  { id: 'cal-3', title: 'Gallery A Lighting Calibration', date: '2026-07-29', type: 'Scheduled Repair', priority: 'Low', department: 'Electrical Technician' },
  { id: 'cal-4', title: 'Conservation Lab Fume Hood Service', date: '2026-07-31', type: 'Maintenance Deadline', priority: 'High', department: 'Artifact Conservation Team' },
  { id: 'cal-5', title: 'Quarterly Elevator & Lift Certification', date: '2026-08-05', type: 'Inspection Date', priority: 'Critical', department: 'Building Maintenance' },
];

export const MAINTENANCE_ANALYTICS_DATA = {
  monthlyRequests: [
    { month: 'Jan', requests: 18, completed: 17 },
    { month: 'Feb', requests: 22, completed: 20 },
    { month: 'Mar', requests: 30, completed: 28 },
    { month: 'Apr', requests: 25, completed: 24 },
    { month: 'May', requests: 28, completed: 26 },
    { month: 'Jun', requests: 35, completed: 33 },
    { month: 'Jul', requests: 24, completed: 21 },
  ],
  categoryBreakdown: [
    { category: 'Artifact Damage', count: 14, percent: '35%' },
    { category: 'Equipment Failure', count: 12, percent: '30%' },
    { category: 'Facility Issue', count: 9, percent: '22%' },
    { category: 'Security Issue', count: 5, percent: '13%' },
  ],
  technicianPerformance: [
    { technician: 'Solomon Worku (IT & HVAC)', tasksAssigned: 14, completed: 13, avgHours: '3.5 hrs' },
    { technician: 'Kebede Alemu (Electrical)', tasksAssigned: 12, completed: 12, avgHours: '2.1 hrs' },
    { technician: 'Girma Tadesse (Building)', tasksAssigned: 16, completed: 15, avgHours: '4.8 hrs' },
    { technician: 'Selamawit Tesfaye (Conservation)', tasksAssigned: 8, completed: 7, avgHours: '8.2 hrs' },
  ],
};
